services:
  synapse:
    image: fractal-matrix-client-synapse:latest
    build:
      context: ./synapse/config
      dockerfile: Dockerfile.synapse
      args:
        SYNAPSE_SERVER_NAME: "localhost"
        SYNAPSE_REPORT_STATS: "no"
    healthcheck:
      test: curl localhost:8008/health
      interval: 1s
      timeout: 10s
      retries: 10
    labels:
      - "org.homeserver.test=true"
    # --timeout on up doesn't work with --exit-code-from. This ensures the synapse
    # container is stopped immediately when the device exits
    stop_signal: SIGKILL
  test:
    image: fractal-matrix-client-test:test
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      synapse:
        condition: service_healthy
    environment:
      ENV: test
      TEST_CONFIG_DIR: /test-config
      TEST_HOMESERVER_URL: http://synapse:8008
      # not actually running a second synapse currently
      TEST_ALTERNATE_HOMESERVER_URL: https://synapse2:8008
      SYNAPSE_DOCKER_LABEL: "org.homeserver.test=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /code
